### PR TITLE
fixing xdebug config setup

### PR DESCRIPTION
**Pull request by mozillalives**

### CODE REVIEW

**Comment by manowark** [comment]
Your PR has been merged. Changes from PR will be synced to the public repository in a few days. Thank you.

**Comment by dewos** [comment]
@manowark could you please update the latest https://hub.docker.com/r/oroinc/php/ image on dockerhub with this one? Thanks

**Comment by dxops** [comment]
@dewos done

**Comment by dewos** [comment]
@dxops thanks

**Pull request closed without merging**
