### PR TITLE
Expose Mailhog to external connection and access, in order to make possible access in browser the Mailhog container

### PR DESCRIPTION
**Pull request by pedrofurtado**
@anyt

With this PR, the user will be able to access `http://localhost:[random-port-that-maps-to-port-1080-of-mailhog-container]`.

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@anyt Is this PR ready for merge?

**Comment by anyt** [comment]
Hi @pedrofurtadoI,
I can merge this only to the `master` branch, as `2.6` is not supported anymore.
Will process till the end of the day.

Thank you.

**Comment by pedrofurtado** [comment]
@anyt Great news! When this PR is merged with `master`, the branch `3.0` also gets this update? Or I need to recreate this PR for this branch too?

**Comment by anyt** [comment]
3.0 branch will not get any updates, as it's a preview version.

**Comment by anyt** [comment]
merged to master https://github.com/oroinc/environment/commit/068d78e5d95192e055f228e2ed2213d9d4ba4efc.

Thank you @pedrofurtado.

**Comment by pedrofurtado** [comment]
@anyt Thanks for feedback! :+1:

**Pull request closed without merging**
